### ISSUE TITLE
[Shrink/PiP] Shrink - Live Preview - Add Crop feature

### ISSUE THREAD

**Issue by gileli121** [WindowTop/WindowTop-App#133]
This is requested by few users in the comments
https://windowtop.info/purchase/

Request:

> I really loved this software. I came across with it because I was trying to solve some issues while streaming on Twitch. I wanted to have my real chat on top of the game, but also, being able to modify transparency and size.
> 
> One thing I’m not sure if its possible: Can you capture an specific part of one window? For example: I would like to capture only the “chat” box of an entire website I’m navigating. It would be interesting if you can “Crop” your selection and then shrink it as a pop up window. Is this possible or it’s not a function implemented on the PRO version?
>
> Once again, thanks a lot for this amazing software

**Comment by PureItTech** [comment]
I too would like to see the ability to "crop" part of an image for the same reasons.
It is helpful many times to have only part of the website "float" (i.e. chat window) instead of the entire website.

**Comment by gileli121** [comment]
@PureItTech 
It is planned for v5.20
This time it is 100%. I am not going to delay it again due to the high votes.

**Comment by gileli121** [comment]
@PureItTech 
Here is some progress from the last days:
![pip-crop-poc-7-3-23](https://user-images.githubusercontent.com/17680514/223276505-79f9576e-6b70-4c5e-bbd7-d758a146eadf.gif)

I am working on the UI for the crop area selector.
There is still some work here

**Comment by PureItTech** [comment]
Thanks!  Looking forward to seeing how this works once released.

**Comment by gileli121** [comment]
@PureItTech 

After a lot of work, here is the updated progress:
![ezgif com-optimize](https://user-images.githubusercontent.com/17680514/226147426-1ae5ff5b-4e7c-40e2-b23d-154f0c886a8c.gif)

I still left with the icon in the toolbar and a few more stuff there.
And also left with updating the mouse-interact feature to work properly when the crop is enabled.

**Comment by camAtGitHub** [comment]
Looks great Gil Eli

**Comment by gileli121** [comment]
The main core behavior about cropping is now finalized (a lot of bug fixes)
The last effort was spent on fixing some bugs in resizing, ratio calculation, and UI event handling of the crop selector controls.
In the next few days, I will move to integration with the "INTERACT" mode.
Currently, the mouse-click forwarding functionality will not take into account the crop state and it needs to be handled.

The last thing that I will work on will be on creating an icon for this button (in the toolbar) and doing more testing and fixes when the DPI configuration is not 100%

**Comment by gileli121** [comment]
@camAtGitHub 
Finished implementing integration with the INTERACT mode, and added an indicator for the crop in the larger preview

https://user-images.githubusercontent.com/17680514/227742608-505802b3-9fde-4faf-ab91-9445d5d0b75d.mp4


How does it look?
I think that I was only left with an icon for the crop button and maybe more few things such as settings (if needed) and small bugfixes for DPI

**Comment by gileli121** [comment]
New video
https://user-images.githubusercontent.com/17680514/227745326-c5d0069d-b6bb-4a0c-9bb6-4caa295dda3d.mp4

**Comment by gileli121** [comment]
@camAtGitHub @PureItTech 
What looks the best here?
![image](https://user-images.githubusercontent.com/17680514/229279627-96489de9-a7cc-4633-ab38-56cc449bf2a6.png)

If you can suggest more from here:
https://www.flaticon.com/search/1?word=crop

**Comment by gileli121** [comment]
@camAtGitHub @PureItTech 

Here is the first beta version with the implementation of https://github.com/WindowTop/WindowTop-App/issues/133
[WindowTop 5.20.0-beta1 - setup.exe.zip](https://github.com/WindowTop/WindowTop-App/files/11131304/WindowTop.5.20.0-beta1.-.setup.exe.zip)

Here is a demo video:

https://user-images.githubusercontent.com/17680514/229336467-943e22bd-2e49-4e5f-a9ae-81595576606e.mp4

Note that I have not yet added the icon for the crop button.
It is hard to figure out what icon to choose.

Other than that, most/all stuff is already implemented and tested as much as I can. 
It should also handle different DPI scaling.

Let me know please how it works.

**Comment by camAtGitHub** [comment]
Hi Gil - Icon options are here: https://github.com/WindowTop/WindowTop-App/issues/287#issuecomment-1493315916

**Comment by gileli121** [comment]
@camAtGitHub @PureItTech 

Here is a new version:

[WindowTop 5.20.0-beta2 - setup.exe.zip](https://github.com/WindowTop/WindowTop-App/files/11142856/WindowTop.5.20.0-beta2.-.setup.exe.zip)

* Implemented support canceling the crop editor when pressing the escape key
* Many fixes and stability improvements for the ratio & size calculation logic were used when applying another crop area
* Avoid some fatal errors (exceptions)
* Fixed wrong position and size calculation of the bigger preview that shows when the features mouse interacts, read mode, and crop enabled. This caused an issue that the bigger preview sometimes was smaller than the actual PiP thumbnail


The icon was not implemented yet.
I will work on it at the end (after everything is tested and working fine)

Let me know how it works for you and if you have any feedback.
Thanks.

**Comment by PureItTech** [comment]
Hi Gil,

One problem – this update doesn’t recognize my serial number as the product was purchased through the Microsoft store.
Can you help?  I cannot install the software because it wants a serial number.

MS Order Number 1860672807 if that helps.

Scott

**Comment by gileli121** [comment]
@PureItTech 
Beta versions do not support Microsoft Store activations because they are not built as MS Store apps.

I can instead reset your 30 days trial. To do it, please go to this path:
%appdata%/windowtop
![image](https://user-images.githubusercontent.com/17680514/230352994-9e5eef4e-bf00-47cd-bd38-434b380fb77b.png)

And open the settings.json file with notepad

Send me the ComputerId value here:
![image](https://user-images.githubusercontent.com/17680514/230353459-46aae134-ad33-4d32-ae66-ffe0eab0f192.png)

And I will use it to reset the trial

**Comment by gileli121** [comment]
Update:
I was hoping to release a new version today.
But as long I continue to test for DPI-related bugs, I find more and more bugs, and it is still very unstable when the DPI is different across monitors.

While developing it, I planned to fix 1-2 more DPI-related bugs. But I find more 9 different bugs.
So there is more work here that may take 1-3 full days before I can consider it stable for DPI cases.

**Comment by PureItTech** [comment]
Hey Gil, I still can’t really use this as it doesn’t recognize my license.
Can you please provide an updated license or something so I can use this and provide feedback/bugs?

Scott

**Comment by gileli121** [comment]
@PureItTech 

Here is a beta version that is unlocked until the 15 of next month:

[WindowTop 5.20.0-beta4 - setup.exe.zip](https://github.com/WindowTop/WindowTop-App/files/11240608/WindowTop.5.20.0-beta4.-.setup.exe.zip)

## Important:
Please uninstall the Microsoft Store version to avoid confusion.
You can install this version in addition to the MS Store version, but you may need help if both versions are installed.


A lot of stuff has improved since the last beta update.
But, unfortunately, it is too much stuff to write.
But I sent here three demo videos that show the progress:

https://user-images.githubusercontent.com/17680514/232251752-64fbc484-83b6-4af9-b06e-e264688ef787.mp4

https://user-images.githubusercontent.com/17680514/232252047-17a9ecf5-7306-43fa-bddc-7f211dca66a3.mp4

https://user-images.githubusercontent.com/17680514/232252259-e0a79a97-3aa5-4d28-adf1-f2cccdb7cd34.mp4


It is still unstable if your monitors have a different resolution scaling (DPI).

Don't expect it to work stably in you have two monitors with different scaling.
For example, if the scaling of the first monitor is 100% and the second one is 250% scaling. It will probably not work stably on the non-primary monitor.

I still needed more time to fix these DPI bugs.
But I will work on it this week.

And there still needs to be an icon. I am waiting for more votes from the survey.

Let me know about and feedback.
Thank you.

**Comment by camAtGitHub** [comment]
Hi Gil,

Icon: of the 5 above I prefer the yellow and red lined icon.

One thing I noticed with the beta versions is: If you PIP a window then tick "Show Original Window" then you un-PIP the window, then PIP the same window again the "Show Original Window" setting is forgotten. Previous versions wouldnt do this and personally I find it quite frustrating that the setting is forgotten.

Cheers

**Comment by gileli121** [comment]
@camAtGitHub 
Yes, it is also clear from the survey that icon 5 is the best option. Most users vote for it.
This is also what I thought to choose.

By the way, I also decided to change the icon of PiP. The icon needs to be a better choice...
At first, it was when the feature called "Shrink"  and did not support a live preview of the actual window.


> One thing I noticed with the beta versions is: If you PIP a window then tick "Show Original Window" then you un-PIP the window, then PIP the same window again the "Show Original Window" setting is forgotten. Previous versions wouldnt do this and personally I find it quite frustrating that the setting is forgotten.

Thanks for the report. 
I will check it later.

Other than that, how the crop functionality works for you so far? Do you like it? Do you have some suggestions?

I will continue to work on it during the weekend.

**Comment by gileli121** [comment]
# Download v5.20-beta5
[WindowTop 5.20.0-beta5 - setup.exe.zip](https://github.com/WindowTop/WindowTop-App/files/11314893/WindowTop.5.20.0-beta5.-.setup.exe.zip)


# New Demo
https://user-images.githubusercontent.com/17680514/234123893-2a6be022-397e-42da-81f1-bea5d3890031.mp4


## UI

* PiP icon changed to: 
![image](https://user-images.githubusercontent.com/17680514/234120254-4f85e12c-6757-49d8-9f41-fc1377139fcf.png)

* Added icon for the crop (added the one that most users picked according to the Survey)
![image](https://user-images.githubusercontent.com/17680514/234120997-fd398cce-fc19-4d94-b18b-48b70b71d65a.png)

## Functionality

* A LOT of bug fixes when having a multi-monitor setup with different scaling per monitor (DPI). Most major DPI bugs should be resolved now.
* Improve the behavior of the crop region selector control. it will react better when selecting a region from an empty state
* Other UI improvements to the crop feature
* Few other DPI bugs like the above, but not specifically about the crop feature
* Anchors feature: improve stability - now it is less likely that anchors will stop to move (in case it was enabled) automatically.


Let me know how it works :)

**Comment by gileli121** [comment]
Here is an updated demo video:
https://user-images.githubusercontent.com/17680514/234341183-542aa272-bc7a-4b77-a9c2-dbc773e228de.mp4

**Comment by gileli121** [comment]
Nice, this is another good idea to implement:

https://www.youtube.com/watch?v=TtPxix5qIcM

https://averagelinuxuser.com/picture-in-picture-elementary/

Just found it while reading users' requests on the P****T*** app.
It seems that it is a thing in Linux-based OS called Elementary OS

I did the same thing, the video suggests a different way to run this function, and I like it.
It should be straightforward to implement it. But I will do it in a separate task, which will not be part of the v5.20 
The following things that I will work on are listed on #287

**Comment by gileli121** [comment]
Created https://github.com/WindowTop/WindowTop-App/issues/295

**Comment by gileli121** [comment]
I am happy to let you know that the development of this feature was completed today!
Here is what I hope to be the final beta with this feature:

https://github.com/WindowTop/WindowTop-App/releases/tag/v5.20.0

Now I will focus primarily on testing it.
Feel free to provide any feedback.

Thanks.

**Comment by PureItTech** [comment]
Thanks can you provide another demo license and/or tell me how to utilize the current one from Windows store?

Scott

**Comment by gileli121** [comment]
@PureItTech 
Did you try the last beta version? It is already unlocked until `Saturday, June 10, 2023`
Download it from here: 
https://github.com/WindowTop/WindowTop-App/releases/download/v5.20.0/WindowTop.5.20.0-beta10.-.setup.exe

About the Microsoft Store version, I am providing this option also now.
If you want to test the version from Microsoft Store, you will need to uninstall the existing version.
After that, go to this [link](https://apps.microsoft.com/store/detail/9NWMQT4L4M94). And from there, you should install it via the store. You should see an app called "WindowTop Beta". You can install it. It will be unlocked until `Saturday, June 10, 2023 `

Note: while I am writing the message, it is still not published to the store, so if you see this:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/a4d03e5a-9881-4047-b4ea-5327fdf9949a)
Please wait some time until it is published.
You should see the name "WindowTop Beta," and it should be free.

**Comment by PureItTech** [comment]
Thanks!  Just FYI, so far everything is working well.  I will reply here if I notice any issues.
Glad you were able to get this done so quickly.

Scott McClannahan
Simple POS Solutions & Pure Technology Inc.
Ext. 121 | Atlanta: 404.993.9438 | Denver: 303.835.0537
***@***.******@***.***>  | Download my business card!<blinq.me/ZvBLmlTAerCE>
Keep IT Pure and Simple

**Comment by gileli121** [comment]
I am glad to do it :)
Do you mean that the crop feature works well?
I think that it should. after all of this effort and testing that I invested into it, I don't expect anything else :) 
But I am ready to fix any good bug (not minor bugs)

**Comment by gileli121** [comment]
@PureItTech 
How it works so far?

**Comment by PureItTech** [comment]
Still working great 😊

Scott McClannahan
Simple POS Solutions & Pure Technology Inc.
Ext. 121 | Atlanta: 404.993.9438 | Denver: 303.835.0537
***@***.******@***.***>  | Download my business card!<blinq.me/ZvBLmlTAerCE>
Keep IT Pure and Simple

**Comment by gileli121** [comment]
Great :)
Getting it right on the first major release is rare but I am not surprised because I tested it so much.

The next development may be this
https://github.com/WindowTop/WindowTop-App/issues/133#issuecomment-1506071900
Feel free to write any suggestions there.

I also created a label for each feature. to see a list of all PiP-related tasks/suggestions, see:
https://github.com/WindowTop/WindowTop-App/issues?q=is%3Aissue+is%3Aopen+label%3AFeature-Picture-in-Picture 

I am closing this issue since it is already done :)

**Comment by PureItTech** [comment]
Hey Gli,

One question I have – is there any way to “interact” with the PIP window?
For example, say I have a chat open that is PIP’d from a website, I’d like to be able to click and type in the PIP window w/o the need to open the website up fully.

is this doable?

Scott McClannahan
Simple POS Solutions & Pure Technology Inc.
Ext. 121 | Atlanta: 404.993.9438 | Denver: 303.835.0537
***@***.******@***.***>  | Download my business card!<blinq.me/ZvBLmlTAerCE>
Keep IT Pure and Simple

**Comment by PureItTech** [comment]
Thanks – I’ll try that!

Scott McClannahan
Simple POS Solutions & Pure Technology Inc.
Ext. 121 | Atlanta: 404.993.9438 | Denver: 303.835.0537
***@***.******@***.***>  | Download my business card!<blinq.me/ZvBLmlTAerCE>
Keep IT Pure and Simple

**Comment by PureItTech** [comment]
Hi there,

I think I had asked/emailed about this previously but are all these features integrated into the version that is currently in the Windows Store?

The reason I ask is that we made the mistake of purchasing through the app store and now the application you had provided a few months ago (BETA) has expired so we can’t run the application with these new features.  The one in the app store seems to be from 2019, so I’m just wondering if there is any way to get these or if I will need to repurchase from your website, which I would prefer to avoid.

Thanks,
Scott

From: Scott McClannahan
Sent: Tuesday, June 6, 2023 2:15 PM
To: 'WindowTop/WindowTop-App' ***@***.***>; 'WindowTop/WindowTop-App' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [WindowTop/WindowTop-App] [Shrink/PiP] Shrink - Live Preview - Add Crop feature (#133)
Importance: Low

Thanks – I’ll try that!

Scott McClannahan
Simple POS Solutions & Pure Technology Inc.
Ext. 121 | Atlanta: 404.993.9438 | Denver: 303.835.0537
***@***.******@***.***>  | Download my business card!<blinq.me/ZvBLmlTAerCE>
Keep IT Pure and Simple

**Comment by gileli121** [comment]
@PureItTech 
The feature was released about 3-4 months ago.
You probably did not receive updates because you installed the wrong version via Microsoft Store.
You will need to uninstall what you have and make sure that it is really uninstalled.
You can by mistake install the version from Microsoft Store and the version from the offline installer.
After you uninstall it, do a second search to make sure that you don't find it anymore.

After that, open Microsoft Store and search for WindowTop and install it from there.
If you don't want to install it via Microsoft Store, you can download and install it regularly from the website.

If you purchase an activation key, you should not have any problem with using the activation key on the Microsoft Store version.
If you purchase it directly from Microsoft Store, you will have to install the Microsoft Store version to use your activation.
To use your activation by Microsoft Store, open the activation settings window. there you should see a button "Purchase or Login (Microsoft Store)". Click on it to log in to your account. if you already purchase it before (via the store), the app will detect and will be activated.

I hope that I helped.
Let me know if you have any more questions.

**Comment by PureItTech** [comment]
Thanks – I think I have this figured out.
Can you confirm if version v5.21.1 is the latest?

Scott

**Comment by PureItTech** [comment]
Hey Gil, just following up on my email below.
Can you confirm if version v5.21.1 is the latest?

Scott

From: Scott McClannahan
Sent: Wednesday, August 23, 2023 8:01 AM
To: WindowTop/WindowTop-App ***@***.***>; WindowTop/WindowTop-App ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [WindowTop/WindowTop-App] [Shrink/PiP] Shrink - Live Preview - Add Crop feature (#133)

Thanks – I think I have this figured out.
Can you confirm if version v5.21.1 is the latest?

Scott

**Comment by gileli121** [comment]
@PureItTech 
Yes
Sorry, I forgot to answer.
I have been very busy in the last few days.

**Comment by gileli121** [comment]
@PureItTech @camAtGitHub 

I am working on major updates for this feature.
I continue the development of it, and it is documented in this topic:

https://github.com/WindowTop/WindowTop-App/issues/313 

Can you please participate in testing and share feedback?
When you have questions/feedback/suggestions - please discuss it in #313 and not here 

You can find beta releases in 

https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.0


Thank you :)
